apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: e2e-test-cert-manager-webhook
webhooks:
- name: e2e-test-cert-manager-webhook.newrelic.com
  rules:
  - apiGroups:
    - "apps"
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - deployments
  clientConfig:
    service:
      namespace: "default"
      name: "no-service"
    caBundle: ""
